training_blocks = [
    ['JAVA', 'JM'],
    ['BTRX', 'BWEB', 'BPATTI', 'BPATTC', 'BCONT', 'BBAY', 'FBTRX'],
    ['CPP', 'info-cpp', 'CPPS', 'CPPM', 'ALGOCPP', 'CPPL', 'SQLCPP', 'MAP', 'DPCPP', 'QT', 'IOT', 'PUE', 'FCPP'],
    ['DEVOPS', 'info-devops', 'MNT', 'DevKub', 'CloKub', 'GIT-DEV', 'VIRTD', 'TER', 'KONF', 'CICD-Dev', 'MON-DEV',
     'MICROS', 'KUBER', 'CLOPRO', 'FDEVOPS'],
    ['PY', 'PYAPI', 'SQLPY'],
    ['FPY', 'FPYMQ', 'FPYJS', 'FPYAJS', 'FPYAHJ', 'FFPY'],
    ['IOS', 'info-ios', 'BIOS', 'IBALGO', 'AIOS', 'IOSUI', 'IOSINT', 'IOSDT', 'IOSADV', 'FIOS'],
    ['NDJS', 'info-ndjs', 'NDSE', 'NDTNF', 'FNDJS'],
    ['NTW', 'info-ntw', 'BNTW', 'RUTSW', 'RSNT', 'DRUT', 'SECNT', 'WFNT', 'QOS', 'CRPNT', 'OPTNT', 'IPNT', 'FNTW'],
    ['ONEC', 'SRK', 'BALGO', 'VY', 'INF', 'SID', 'REGIS', 'FILE', 'RNFD', 'IND', 'MA', 'PV', 'BPZ', 'DTK', 'BSP',
     'OCEDT', 'TAT', 'MROC', 'OCPS'],
    ['PAE', 'PBAS', 'PWIN', 'PNET', 'SCADA', 'PHD', 'CODEPLC', 'PIB', 'PMS'],
    ['QAMID', 'FAQA', 'JSQA', 'JSAQA', 'MQA', 'LOADQA', 'IBQA'],
    ['SIB', 'INFOSIB', 'IBB', 'IBNET', 'IBGIT', 'IBOS', 'IBDEV', 'IBWEB', 'IBDEF', 'IBMOD', 'IBINC'],
    ['SQLD', 'SQLSLIN', 'SQLBASH', 'DWH-SQLD', 'SQLSDB', 'SQLDB'],
    ['SYS', 'SRLB', 'SDB', 'SLINA', 'SLINB', 'SLINC', 'NET', 'BASH', 'SVIRT', 'CICD', 'SMON', 'SFLT', 'SYSDB', 'SDBSQL',
     'SYSSEC', 'SLINA-LINUX', 'NET-LINUX', 'COURSE-FOPS', 'GIT-FOPS', 'BD-DEV']
]
