nickname_expert = {
    'Азамат Искаков': '@azamat_iskakov',
    'Александр Бардин': '@a.a.bardin',
    'Александр Голубь': '@ goluba',
    'Александр Домнин': '@ alexandr_domnin',
    'Александр Дудинский': '@dooalex',
    'Александр Зубарев': '@alexzubarev',
    'Александр Иванов': '@artrey',
    'Александр Киявин': '@aleksandr_kiyavin',
    'Александр Мужев': '@aleksandrmuzhev',
    'Александр Нагернюк': '@nagernuke',
    'Александр Сенин': '@senin',
    'Александр Тушнов': '@alexandrtushnov',
    'Александр Федоров': '@afedorov',
    'Алексей Бардин': '@bardincom',
    'Алексей Леонов': '@axelerleo',
    'Алексей Лутков': '@alexey_lutkov',
    'Алексей Миронов': '@alexey_m',
    'Алексей Павлов': '@newager',
    'Алексей Перерва': '@a.pererva',
    'Алексей Титов': '@alex.titov',
    'Алексей Федин': '@memorilik',
    'Алёна Батицкая': '@abatickaya',
    'Амиран Мстоян': '@am_i_ami',
    'Анастасия Бердникова': '@berdnikovacoach',
    'Анастасия Огаркова': '@a.ogarkowa',
    'Анатолий Слабоденюк': '@anatoly_slabodenyuk',
    'Анатолий Спитченко': '@anatolii_spitchenko',
    'Анатолий Сюняев': '@a.syunyaev',
    'Андрей Бирюков': '@andrey_biryukov',
    'Андрей Борисов': '@clinri',
    'Андрей Гаретов': '@garetov_andrew',
    'Андрей Денисов': '@andrey4822',
    'Андрей Каныгин': '@andreykanygin',
    'Андрей Кондрашов': '@akondrashov',
    'Андрей Пахомов': '@andrew_pahomov',
    'Андрей Тряпичников': '@andrei.triapichnikov',
    'Андрей Хомутов': '@homutovan',
    'Андрей Чередников': '@andreycherednikov',
    'Анна Восканян': '@anna_voskanyan',
    'Анна Крылова': '@an.krylova',
    'Анна Русяева': '@annarsve',
    'Антон Абрамов': '@lexxarh',
    'Антон Банков': '@ffh2000',
    'Антон Ласточкин': '@antlas',
    'Антон Парамонов': '@aparam1991',
    'Антон Чаусов': '@chausovanton',
    'Арсений Сова': '@arseniy_sova',
    'Артем Дагриджан': '@berserk',
    'Артём Качалкин': '@anarakinson',
    'Артем Мостяев': '@raistlin',
    'Артем Недвигин': '@filipanselmo',
    'Артём Романов': '@arromanov',
    'Артур Сагутдинов': '@adminguide',
    'Артур Сапрыкин': '@arthur_saprykin',
    'Булат Замилов': '@bulatzamilov',
    'Валерий Линьков': '@babaika',
    'Виктор Кузьмин': '@imvikuz',
    'Владимир Липатов': '@imperialag',
    'Владимир Языков': '@neizerth',
    'Владислав Кочетков': '@llouqs',
    'Влад Уткин': '@vlad_utkin',
    'Владислав Хорев': '@mephi1984',
    'Вячеслав Герасименко': '@uberhahn',
    'Георгий Власов': '@honest_niceman',
    'Герман Дудченко': '@german_dudchenko',
    'Григорий Вахмистров': '@grigorii_vakhmistrov',
    'Дамир Рысаев': '@freepad',
    'Данил Карандин': '@danil',
    'Данила Исаев': '@isa3v',
    'Дарья Татькова': '@daryatatkova',
    'Денис Альмухаметов': '@denops',
    'Денис Владимиров': '@denizen24',
    'Дмитрий Бронских': '@d.bronskih',
    'Дмитрий Качалов': '@kachalov_dmitry',
    'Дмитрий Лин': '@dmitrii.lin',
    'Дмитрий Перьков': '@dmitry_perkov',
    'Дмитрий Столяров': '@dmitrii_stoliarov',
    'Дмитрий Тишкевич': '@dmitrii_tishkevich',
    'Дмитрий Томин': '@dtomin.pro',
    'Дмитрий Шанин': '@rofey',
    'Евгений Варламов': '@evgeniy-varlamov',
    'Евгений Корытов': '@korytoff',
    'Евгений Мисяков': '@e.misiakov',
    'Евгений Шмаргунов': '@eshmargunov',
    'Евгения Волова': '@evgenia_volova',
    'Егор Наумов': '@egor_nmv',
    'Екатерина Борушная': '@kattiona',
    'Елена Скрипаль': '@elena_skripal',
    'Елисей Ильин': '@elisey_ilyin',
    'Ибрагим Гусейнов': '@gus1bra',
    'Иван Родин': '@ivanrodin',
    'Игорь Александров': '@igor_aleksandrov',
    ' Игорь Крамер': '@igor.kramer',
    'Игорь Мартюшев': '@aeegon',
    'Игорь Сверчков': '@knjaz1989',
    'Игорь Симдянов': '@igorsimdyanov',
    'Игорь Цаллагов': '@igor.tsallagov',
    'Ильмир Сахипов': '@ilmir',
    'Касаткин Кирилл': '@minky',
    'Кирилл Константинов': '@lirik789',
    'Кирилл Лежнев': '@kirillqa',
    'Кирилл Незнанов': '@komroden',
    'Кирилл Попов': '@kirill.popov',
    'Кирилл Табельский': '@kirill',
    'Константин Харитонов': '@konstantin_kharitonov',
    'Ксения Дикова': '@kseniia_dikova',
    'Ксения Ильина': '@k.ilina',
    'Любовь Маясова': '@liubov',
    'Максим Анненков': '@maxon18071975',
    'Максим Воронцов': '@maksim.vorontsov',
    'Марат Гайнутдинов': '@maratgainutdinov',
    'Марина Матюшина': '@marina.matyushina',
    'Мария Кожанова': '@mariakozhanova',
    'Мария Логунова': '@mariya_logunova',
    'Матвей Серегин': '@matvey.seregin',
    'Михаил Карацюба': '@karasiubamihail',
    'Михаил Сизов': '@msizov',
    'Наталия Исакова': '@linart87',
    'Наталья Синицына': '@nsinicina',
    'Ника Лобанова': '@nika_lobanova',
    'Никита Балясный': '@nikita.baliassniy',
    'Никита Гололобов': '@gololobovn',
    'Никита Зарубин': '@nikita_zarubin',
    'Никита Никифоров': '@kefear_kuban',
    'Никита Янченков': '@nikiyani',
    'Николай Хащанов': '@nkh',
    'Нияз Кашапов': '@niyazkashapov',
    'Олег Булыгин': '@oleg',
    'Ольга Голубева': '@olga_golubeva',
    'Ольга Ермолова': '@o_ermolova',
    'Ольга Кащеева': '@olgasaveleva',
    'Павел Беляев': '@polo',
    'Павел Бондаренко': '@pashabond',
    'Павел Козлов': '@pavel_kozlov',
    'Павел Молибог': '@mpi333',
    'Павел Пронин': '@papavel_152',
    'Петр Лосев': '@petrlosev',
    'Петр Скворцов': '@petr.skvortsov',
    'Ринат Бибиков': '@netology_777',
    'Роман Лешин': '@jomarzka',
    'Руслан Мамедов': '@ruslan_mammadov',
    'Руслан Султанов': '@ruslan',
    'Семен Поляков': '@semionpoliakov',
    'Сергей Алексеев': '@sergey_alekseev',
    'Сергей Бреусенков': '@sbreusenkov',
    'Сергей Котов': '@serge_kotov',
    'Сергей Родионов': '@rodionov_s',
    'Сергей Розанов': '@sergey_rozanov',
    'Сергей Рудик': '@rudik',
    'Сергей Шумов': '@sergeyshumov',
    'Тамби Мерза': '@bitrix-developer',
    'Тимур Анвартдинов': '@anvartdinovtimur',
    'Тимур Саидов': '@tfsaidov',
    'Феликс Антуфьев': '@felix.antufiev',
    'Филипп Воронов': '@fivoronov',
    'Филипп Сенцов': '@filipp-sentsov',
    'Эльвира Ежова': '@elisvelis',
    'Юлия Пономарева': '@julia_ponomareva',
    'Юрий Копшев': '@yuri_kopshev',
    'Ярослав Сапронов': '@sapronov_yaroslav',
    'Alexey Smagin': '@alexsmagin',
    'Daniil Korbut': '@rtraingle',
    'Ekaterina Prokhorova': '@catprokhorova',
    'Erick Arais': '@arais_erick',
    'Ivan Aniskovets': '@ivan_aniskovets',
    'Vadim Bashurov': '@vadim_bashurov',
    'Vladimir Novikov': '@vnovikov',
    'Yana Kurenchanina': '@yanakurenchanina',

    'non_name': ['@a.andrukhov',
                 '@aleksandr_kiyavin',
                 '@addirossi',
                 '@alex_kuzmin',
                 '@alsdew',
                 '@anatoliisolovev',
                 '@artem_ponevin',
                 '@bor_bor_',
                 '@dbutuzova',
                 '@e_konyagin',
                 '@egorshishkovets',
                 '@ekaterina_shestakova',
                 '@elena.',
                 '@igor.kramer',
                 '@inessa_kochetkova',
                 '@itemius',
                 '@kbashevoy',
                 '@kriventsovvg',
                 '@litvinova',
                 '@msakharov',
                 '@nataliasiakatskaya',
                 '@nataliaskorikova',
                 '@sandraelagina',
                 '@sasha_gorbunova',
                 '@svetlana19',
                 '@tora',
                 '@vanyabocharov',
                 '@vyacheslav_potapov',
                 '@pavel_kozlov']
}
